matrix:
  include:
    - language: python
      os: linux
      env: DEPLOY=true
      python: 3.6
    - language: python
      os: linux
      env: DEPLOY=false
      python: 3.7-dev
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -r --upgrade requirements-dev.txt
script:
  - make test
after_success:
  - codecov
deploy:
  provider: pypi
  user: ohjeah
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    all_branches: true
    condition: $DEPLOY = true
