language: python
python:
  - "3.5"
  - "3.6"
install: make dev
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
     rooms:
       - ambrosys:$SLACK_TOKEN
     on_success: always
  email: false
