language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - py.test tests --cov=glyph --cov-config=setup.cfg
after_success:
  - codecov
deploy:
  provider: pypi
  user: ohjeah
  password: $PYPI_PW
  on:
    tags: true
    python: "3.6"
    all_branches: true
