language: python
python:
  - "3.5"
# command to install dependencies
install: make dev
# command to run tests
script: make test

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

notifications:
  slack:
     rooms:
       - ambrosys:$SLACK_TOKEN
     on_success: always
  email: false
