language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - py.test tests --cov=glyph --cov-config setup.cfg
after_success:
  - codecov
notifications:
  slack:
     rooms:
       - ambrosys:$SLACK_TOKEN
     on_success: always
  email: false
